version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  app:
    build: .
    container_name: notes-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - backend-network

volumes:
  mongo_data:  # This volume will persist MongoDB data across restarts

networks:
  backend-network:
    driver: bridge
